// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: lobby/lobby.proto

package lobby

import (
	common "github.com/tanerius/dungeonforge/src/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *common.BaseResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Info     *LobbyInfoResponse   `protobuf:"bytes,2,opt,name=info,proto3,oneof" json:"info,omitempty"`
	Motd     *string              `protobuf:"bytes,3,opt,name=motd,proto3,oneof" json:"motd,omitempty"`
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_lobby_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_lobby_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_lobby_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *JoinResponse) GetResponse() *common.BaseResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *JoinResponse) GetInfo() *LobbyInfoResponse {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *JoinResponse) GetMotd() string {
	if x != nil && x.Motd != nil {
		return *x.Motd
	}
	return ""
}

type LeaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *common.BaseResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Msg      *string              `protobuf:"bytes,2,opt,name=msg,proto3,oneof" json:"msg,omitempty"`
}

func (x *LeaveResponse) Reset() {
	*x = LeaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_lobby_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveResponse) ProtoMessage() {}

func (x *LeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_lobby_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveResponse.ProtoReflect.Descriptor instead.
func (*LeaveResponse) Descriptor() ([]byte, []int) {
	return file_lobby_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *LeaveResponse) GetResponse() *common.BaseResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *LeaveResponse) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

type LobbyInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response     *common.BaseResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Id           string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Type         int64                `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	UsersCurrent int64                `protobuf:"varint,4,opt,name=usersCurrent,proto3" json:"usersCurrent,omitempty"`
	UsersMaximum int64                `protobuf:"varint,5,opt,name=usersMaximum,proto3" json:"usersMaximum,omitempty"`
	Region       string               `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Language     string               `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	GameId       string               `protobuf:"bytes,8,opt,name=gameId,proto3" json:"gameId,omitempty"`
}

func (x *LobbyInfoResponse) Reset() {
	*x = LobbyInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_lobby_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LobbyInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyInfoResponse) ProtoMessage() {}

func (x *LobbyInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_lobby_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyInfoResponse.ProtoReflect.Descriptor instead.
func (*LobbyInfoResponse) Descriptor() ([]byte, []int) {
	return file_lobby_lobby_proto_rawDescGZIP(), []int{2}
}

func (x *LobbyInfoResponse) GetResponse() *common.BaseResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *LobbyInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LobbyInfoResponse) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *LobbyInfoResponse) GetUsersCurrent() int64 {
	if x != nil {
		return x.UsersCurrent
	}
	return 0
}

func (x *LobbyInfoResponse) GetUsersMaximum() int64 {
	if x != nil {
		return x.UsersMaximum
	}
	return 0
}

func (x *LobbyInfoResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *LobbyInfoResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *LobbyInfoResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type RollRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dice  int64 `protobuf:"varint,1,opt,name=dice,proto3" json:"dice,omitempty"`
	Sides int64 `protobuf:"varint,2,opt,name=sides,proto3" json:"sides,omitempty"`
}

func (x *RollRequest) Reset() {
	*x = RollRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_lobby_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollRequest) ProtoMessage() {}

func (x *RollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_lobby_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollRequest.ProtoReflect.Descriptor instead.
func (*RollRequest) Descriptor() ([]byte, []int) {
	return file_lobby_lobby_proto_rawDescGZIP(), []int{3}
}

func (x *RollRequest) GetDice() int64 {
	if x != nil {
		return x.Dice
	}
	return 0
}

func (x *RollRequest) GetSides() int64 {
	if x != nil {
		return x.Sides
	}
	return 0
}

type RollResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *common.BaseResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Value    []int64              `protobuf:"varint,2,rep,packed,name=value,proto3" json:"value,omitempty"`
}

func (x *RollResponse) Reset() {
	*x = RollResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_lobby_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollResponse) ProtoMessage() {}

func (x *RollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_lobby_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollResponse.ProtoReflect.Descriptor instead.
func (*RollResponse) Descriptor() ([]byte, []int) {
	return file_lobby_lobby_proto_rawDescGZIP(), []int{4}
}

func (x *RollResponse) GetResponse() *common.BaseResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *RollResponse) GetValue() []int64 {
	if x != nil {
		return x.Value
	}
	return nil
}

type UserEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Displayname string `protobuf:"bytes,2,opt,name=displayname,proto3" json:"displayname,omitempty"`
}

func (x *UserEntry) Reset() {
	*x = UserEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_lobby_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEntry) ProtoMessage() {}

func (x *UserEntry) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_lobby_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEntry.ProtoReflect.Descriptor instead.
func (*UserEntry) Descriptor() ([]byte, []int) {
	return file_lobby_lobby_proto_rawDescGZIP(), []int{5}
}

func (x *UserEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserEntry) GetDisplayname() string {
	if x != nil {
		return x.Displayname
	}
	return ""
}

type UserListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *common.BaseResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Users    []*UserEntry         `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *UserListResponse) Reset() {
	*x = UserListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_lobby_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResponse) ProtoMessage() {}

func (x *UserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_lobby_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResponse.ProtoReflect.Descriptor instead.
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return file_lobby_lobby_proto_rawDescGZIP(), []int{6}
}

func (x *UserListResponse) GetResponse() *common.BaseResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *UserListResponse) GetUsers() []*UserEntry {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_lobby_lobby_proto protoreflect.FileDescriptor

var file_lobby_lobby_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x91, 0x01, 0x0a, 0x0c, 0x4a, 0x6f, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x88, 0x01, 0x01, 0x12,
	0x17, 0x0a, 0x04, 0x6d, 0x6f, 0x74, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x04, 0x6d, 0x6f, 0x74, 0x64, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6d, 0x6f, 0x74, 0x64, 0x22, 0x59, 0x0a, 0x0d, 0x4c, 0x65,
	0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a,
	0x04, 0x5f, 0x6d, 0x73, 0x67, 0x22, 0xf6, 0x01, 0x0a, 0x11, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x73, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x22,
	0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x73, 0x4d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x73, 0x4d, 0x61, 0x78, 0x69, 0x6d,
	0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x37,
	0x0a, 0x0b, 0x52, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x64, 0x69, 0x63,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x69, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x73, 0x69, 0x64, 0x65, 0x73, 0x22, 0x4f, 0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3d, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x5f, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x32, 0xee, 0x01, 0x0a, 0x0c, 0x4c, 0x6f, 0x62,
	0x62, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0d, 0x2e, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x4c, 0x6f, 0x62,
	0x62, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x0d, 0x2e, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x09,
	0x4a, 0x6f, 0x69, 0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x0d, 0x2e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x0a, 0x4c, 0x65, 0x61, 0x76, 0x65,
	0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x0d, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x6c, 0x12, 0x0c, 0x2e, 0x52,
	0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x52, 0x6f, 0x6c,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x6e, 0x65, 0x72, 0x69, 0x75, 0x73,
	0x2f, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x66, 0x6f, 0x72, 0x67, 0x65, 0x2f, 0x73, 0x72,
	0x63, 0x2f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x3b, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lobby_lobby_proto_rawDescOnce sync.Once
	file_lobby_lobby_proto_rawDescData = file_lobby_lobby_proto_rawDesc
)

func file_lobby_lobby_proto_rawDescGZIP() []byte {
	file_lobby_lobby_proto_rawDescOnce.Do(func() {
		file_lobby_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(file_lobby_lobby_proto_rawDescData)
	})
	return file_lobby_lobby_proto_rawDescData
}

var file_lobby_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_lobby_lobby_proto_goTypes = []any{
	(*JoinResponse)(nil),        // 0: JoinResponse
	(*LeaveResponse)(nil),       // 1: LeaveResponse
	(*LobbyInfoResponse)(nil),   // 2: LobbyInfoResponse
	(*RollRequest)(nil),         // 3: RollRequest
	(*RollResponse)(nil),        // 4: RollResponse
	(*UserEntry)(nil),           // 5: UserEntry
	(*UserListResponse)(nil),    // 6: UserListResponse
	(*common.BaseResponse)(nil), // 7: BaseResponse
	(*common.TokenRequest)(nil), // 8: TokenRequest
}
var file_lobby_lobby_proto_depIdxs = []int32{
	7,  // 0: JoinResponse.response:type_name -> BaseResponse
	2,  // 1: JoinResponse.info:type_name -> LobbyInfoResponse
	7,  // 2: LeaveResponse.response:type_name -> BaseResponse
	7,  // 3: LobbyInfoResponse.response:type_name -> BaseResponse
	7,  // 4: RollResponse.response:type_name -> BaseResponse
	7,  // 5: UserListResponse.response:type_name -> BaseResponse
	5,  // 6: UserListResponse.users:type_name -> UserEntry
	8,  // 7: LobbyService.GetServiceInfo:input_type -> TokenRequest
	8,  // 8: LobbyService.GetUsers:input_type -> TokenRequest
	8,  // 9: LobbyService.JoinLobby:input_type -> TokenRequest
	8,  // 10: LobbyService.LeaveLobby:input_type -> TokenRequest
	3,  // 11: LobbyService.Roll:input_type -> RollRequest
	2,  // 12: LobbyService.GetServiceInfo:output_type -> LobbyInfoResponse
	6,  // 13: LobbyService.GetUsers:output_type -> UserListResponse
	0,  // 14: LobbyService.JoinLobby:output_type -> JoinResponse
	1,  // 15: LobbyService.LeaveLobby:output_type -> LeaveResponse
	4,  // 16: LobbyService.Roll:output_type -> RollResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_lobby_lobby_proto_init() }
func file_lobby_lobby_proto_init() {
	if File_lobby_lobby_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lobby_lobby_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*JoinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_lobby_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*LeaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_lobby_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*LobbyInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_lobby_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*RollRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_lobby_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*RollResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_lobby_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UserEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_lobby_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UserListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_lobby_lobby_proto_msgTypes[0].OneofWrappers = []any{}
	file_lobby_lobby_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lobby_lobby_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lobby_lobby_proto_goTypes,
		DependencyIndexes: file_lobby_lobby_proto_depIdxs,
		MessageInfos:      file_lobby_lobby_proto_msgTypes,
	}.Build()
	File_lobby_lobby_proto = out.File
	file_lobby_lobby_proto_rawDesc = nil
	file_lobby_lobby_proto_goTypes = nil
	file_lobby_lobby_proto_depIdxs = nil
}
