name: myapp

services:
  haxe:
    build:
      context: ./haxe
    working_dir: /app
    command: > 
      haxelib run protohx generate protohx.json
      && haxe ./build.hxml
    volumes:
      - ./haxe/app:/app
    profiles:
      - donotstart
  lobby:
    build:
      context: .
    ports:
      - 8080:8080
    profiles:
      - donotstart
  mongo:
    image: mongo:latest
    restart: on-failure
    ports:
      - "27017:27017" # Expose port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: dungeonmaster
      MONGO_INITDB_ROOT_PASSWORD: m123123123
      MONGO_INITDB_DATABASE: dungeondb
      GAME_USER_PASS: gameuserpass
    volumes:
      - mongodb-data:/data/db
      - mongodb-log:/var/log/mongodb
      - ./init-script:/docker-entrypoint-initdb.d
    profiles:
      - donotstart
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: dungeonmaster
      ME_CONFIG_MONGODB_ADMINPASSWORD: m123123123
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_URL: mongodb://dungeonmaster:m123123123@mongo:27017/
    profiles:
      - donotstart
volumes:
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local
